set -g mouse on
set -g prefix C-a

# bind C-s send C-s
bind C-a send C-a
set -g mode-keys vi
set -g allow-passthrough on
set -a terminal-features 'xterm-256color:RGB'
set -g history-limit 50000
setw -g aggressive-resize on

# set -g extended-keys on
# set -g extended-keys-format csi-u

# set -g base-index 1 # window index increse from 1
set -g renumber-windows on

set -s set-clipboard on # Support OSC52

set -g status-position top
set -g status-style "bg=default"
set -g status-justify absolute-centre
set -g window-status-current-style "fg=red bold"
set -g status-right ""
set -g status-left "#S"
set -g window-status-separator "  "

bind r source-file ~/.config/tmux/tmux.conf \; display "Source config file: ~/.config/tmux/tmux.conf"

# Should config terminal send \e[32;5;32~ when press Ctrl+Shift+Space
# bind-key -n "\e[32;5;32~" copy-mode
bind m set -g mouse \; display "Mouse Mode: #{?mouse,ON,OFF}"

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi i send -X cancel

# bind-key -n M-O resize-pane -Z
bind-key -n C-Tab last-window
# bind-key -n C-BTab previous-window

bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9
bind -n M-0 select-window -t :0

bind-key Enter copy-mode \; send-keys -X start-of-line
bind-key -n C-Enter copy-mode \; send-keys -X start-of-line

# bind-key -n C-\\ if-shell -F '#{==:#{session_name},popup}' {
#     detach-client
# } {
#     display-popup -d "#{pane_current_path}" -xC -yC -w60% -h70% -E \
#     'tmux new -s popup && tmux kill-session -t popup || true'
# }

bind-key -n C-\\ display-popup \
    -d "#{pane_current_path}" \
    -xC -yC \
    -w70% -h80% \
    -E 'bash'

########### tmux fingers ###########
# $ git clone https://github.com/Morantron/tmux-fingers ~/.tmux/plugins/tmux-fingers
run-shell ~/.tmux/plugins/tmux-fingers/tmux-fingers.tmux

bind -n M-F run -b "#{@fingers-cli} start #{pane_id}"
bind -n M-J run -b "#{@fingers-cli} start #{pane_id} --mode jump"

# Start tmuxles/tmux/.config/tmux/tmux.conf fingers in jump mode by pressing Alt+J
####################################
