font=Iosevka Nerd Font Mono:size=13, Noto Sans CJK SC:size=13
pad=0x0

[csd]
size = 0

[colors]
# zenburn, terminal.sexy
foreground=ffffff
background=000000
alpha=1.0

regular0=1e2320
regular1=705050
regular2=60b48a
regular3=dfaf8f
regular4=506070
regular5=dc8cc3
regular6=8cd0d3
regular7=dcdccc

bright0=709080
bright1=dca3a3
bright2=c3bf9f
bright3=f0dfaf
bright4=94bff3
bright5=ec93d3
bright6=93e0e3
bright7=ffffff
