set number "relativenumber
" set list listchars=tab:»\ ,trail:·,nbsp:␣,precedes:<,extends:>
set wrap
set splitbelow splitright
set ignorecase smartcase
set smarttab smartindent
set noerrorbells vb t_vb=		" 删除烦人的铃声和闪烁
set hidden				" 允许在有未保存更改的情况下切换到其他缓冲区
set hlsearch				" 高亮搜索结果
" set autochdir
set foldmethod=indent foldlevel=1000
set formatoptions+=Mm " include the chinese charactor
set grepprg=rg\ --vimgrep\ --no-heading
set exrc

filetype plugin indent on

set background=dark
" colorscheme habamax
colorscheme retrobox

set clipboard=unnamedplus
" WSL clipboard config
"autocmd TextYankPost * call system('win32yank.exe -i --crlf', @")
"function! Paste(mode)
"	let @" = system('win32yank.exe -o --lf')
"	return a:mode
"endfunction
"map <expr> p Paste('p')
"map <expr> P Paste('P')

" some version vim doesn't hava Wayland support
" nnoremap <C-@> :call system("wl-copy", @")<CR>

nnoremap c "_c
nnoremap Y y$
nnoremap j gj
nnoremap k gk

" Linux ibus config
" autocmd InsertLeave * silent! execute "!ibus engine xkb:us::eng" | redraw!

set path+=** wildignore+=*/node_modules/*,*/.git/*,*/.svn/*


runtime! defaults.vim
runtime! ftplugin/man.vim " :Man
packadd! matchit
packadd! nohlsearch
packadd! hlyank
packadd! editorconfig
packadd! editexisting
packadd! cfilter
packadd! comment

" In vim, use esc to map <m-x>
" nnoremap <C-h> <C-w>h
" nnoremap <C-j> <C-w>j
" nnoremap <C-k> <C-w>k
" nnoremap <C-l> <C-w>l

let g:mapleader = ' '

xnoremap * "yy/<C-r>y<cr>
xnoremap # "yy?<C-r>y<cr>
" nnoremap <leader><leader> :
let @f = "gggqG"
nnoremap + <cmd>make<cr>

" Quickfix
noremap <leader>c <cmd>cw<cr>
noremap <leader>C <cmd>cclose<cr>
nnoremap ]q :cnext<cr>
nnoremap [q :cprev<cr>

function! CopyVisualButNoContent()
  let start_line = line("'<")
  let end_line   = line("'>")
  normal! \<Esc>
  let file_path = expand("%:p:~")
  if start_line == end_line
    let text = file_path . ":" . start_line
  else
    let text = file_path . ":" . start_line . "," . end_line
  endif
  let @+ = text
  echo "Copied: " . text
endfunction
xnoremap <silent> Y :<c-u>call CopyVisualButNoContent()<cr>
nnoremap <silent> yp :let @+ = expand("%:p:~")<cr>

nnoremap <leader>x :terminal ++curwin 
nnoremap <leader>X :below terminal 
nnoremap <leader>q <cmd>quit<cr>
nnoremap <leader>d <cmd>bd<cr>
nnoremap <leader>w <cmd>write<cr>
nnoremap <leader>b :ls<cr>:b 

" set quickfix height to 5
au FileType qf 6wincmd _

call plug#begin()
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sleuth'  " Automatically adjusts tab settings
" Plug 'tpope/vim-vinegar'
Plug 'chriszarate/yazi.vim'

Plug 'SirVer/ultisnips'
Plug 'adriaanzon/vim-emmet-ultisnips'

Plug 'voldikss/vim-translator'

Plug 'tpope/vim-repeat'
Plug 'kkew3/jieba.vim', { 'branch': 'release', 'do': { -> jieba_vim#install() } }

Plug 'lervag/vimtex'
call plug#end()

let g:fzf_vim = {}
" let g:fzf_vim.preview_window = ['down,50%', 'ctrl-/']

nnoremap <leader>sf :Files 
nnoremap <leader>f <cmd>Files<cr>
nnoremap <leader>sF :GFiles 
nnoremap <leader>sg :Rg 
nnoremap <leader>r <cmd>Rg<cr>
nnoremap <leader>sl :BLines 
nnoremap <leader>l <cmd>BLines<cr>
nnoremap <leader>sL :Lines 
nnoremap <leader>sh :History<cr>
nnoremap <leader>, :Buffers<cr>

nnoremap <leader>g <cmd>G ++curwin<cr>

nnoremap <silent> - :Yazi<cr>
nnoremap <silent> _ :YaziWorkingDirectory<cr>

nnoremap <silent> <Leader>t <Plug>Translate
vnoremap <silent> <Leader>t <Plug>TranslateV

let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'
let g:netrw_banner = 0 " Hide the banner

let g:jieba_vim_keymap = 1


function! s:Translate() range
  let l:text = join(getline(a:firstline, a:lastline), "\n")
  let l:out  = systemlist('trans', l:text)
  if empty(l:out)
    let l:out = ['']
  endif

  execute 'vertical rightbelow new'
  setlocal buftype=nofile bufhidden=wipe noswapfile
  call setline(1, l:out)
  file DeepSeek_Translate
endfunction

vnoremap <silent> <leader>t :call <SID>Translate()<CR>
